### ISSUE TITLE
Incorrect encoding of some file Russian language

### ISSUE THREAD

**Issue by AgelxNash** [ClipperCMS/ClipperCMS#375]
http://take.ms/2RtP9

**Comment by AgelxNash** [comment]
similar tickets: #360 and #362

**Comment by akool** [comment]
A similar problem in Res Manager module.
Сan be solved if delete a file russian.inc.php and rename russian-utf8.inc.php to russian.inc.php

**Comment by TimGS** [comment]
This should now be fixed in the develop branch for both the manager core and Resmanager. 

Please confirm - although it looks OK to me, I can't read Russian.

**Comment by akool** [comment]
I updated all the changed files, added new files. It seems that everything OK.
But problem with encoding in TinyMCE configuration is not solved. http://take.ms/2RtP9
This problem is solved as in ResManager module. Delete and rename files in /assets/plugins/tinymce/lang/

**Comment by TimGS** [comment]
Update.... I have pushed a commit to develop which should solve this issue for UTF-8.

Other encodings e.g. windows-1251 will need to wait for #366 to be fixed (coming soon!)

**Comment by akool** [comment]
I`m using UTF-8.
